# Generated by Django 4.1 on 2023-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('title', models.CharField(default='No Title', max_length=255)),
                ('body', models.CharField(default='', max_length=10000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
