# Generated by Django 4.1 on 2023-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
