# Generated by Django 4.1 on 2023-02-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='username',
        ),
    ]
